Загрузки/моя курсовая/base_app-master/config/routes.rb
Rails.application.routes.draw do
  post 'fill_result_form' => 'surveys#fill_result_form'
  post 'fill_ward_form' => 'surveys#fill_ward_form'
  post 'fill_card_form' => 'surveys#fill_card_form'

  resources :results
  resources :surveys
  resources :wards
  resources :cards do
     collection do
       get :search
     end
   end
  resources :role_users
  resources :roles
  resources :password_resets

  get 'welcome/index', as: :welcome
  get 'welcome/insufficient_privileges', as: :ip
  get 'login' => 'welcome#new', :as => :login
  get 'logout' => 'welcome#destroy', :as => :logout
  post 'try_login' => 'welcome#create', :as => :try_login
  root 'welcome#index'

  resources :users do
    member do
      get :activate
    end
  end

end

Загрузки/моя курсовая/base_app-master/app/models/card.rb
class Card < ActiveRecord::Base
  has_many :survey, dependent: :destroy


  validates :second_name, presence:true, length: {maximum: 30}
  validates :first_name, presence:true, length: {maximum: 30}
  validates :last_name, presence:true, length: {maximum: 30}
  validates :passport, presence:true, length: {maximum: 30},
  uniqueness:true
  validates :insurance, presence:true, uniqueness:true
  validates :residence, presence:true, inclusion:
  { in: ['besplatnoe', 'platnoe'] }
  validates :created, presence:true
  validates :allergy, presence:true, length: {maximum: 128}
  validates :cart_number, presence:true, uniqueness:true, numericality:
  {only_integer: true, greater_than_or_equal_to: 0}

  def self.search(params)
     result = Card.includes(:survey).includes(:survey => :ward).includes(:survey => :result).references(:survey).references(:survey => :ward).references(:survey => :result)
     if params['second_name'].present?
       result = result.where(second_name: params['second_name'])
     end
     if params['first_name'].present?
       result = result.where(first_name: params['first_name'])
     end
     if params['last_name'].present?
       result = result.where(last_name: params['last_name'])
     end
     if params['passport'].present?
       result = result.where(passport: params['passport'])
     end
     if params['insurance'].present?
       result = result.where(insurance: params['insurance'])
     end
     if params['residence'].present?
       result = result.where(residence: params['residence'])
     end
     if params['created'].present?
       result = result.where(created: params['created'])
     end
     if params['allergy'].present?
       result = result.where(allergy: params['allergy'])
     end
     if params['cart_number'].present?
       result = result.where(cart_number: params['cart_number'])
     end


     if params['survey'].present?
       result = result.where(survey: params['survey'])
     end


     #Wards

     if params['department'].present?
       result = result.where(wards: {department: params['department']})
     end
     if params['floor'].present?
       result = result.where(wards: {floor: params['floor']})
     end
     if params['capacity'].present?
       result = result.where(wards: {capacity: params['capacity']})
     end
     if params['number'].present?
       result = result.where(wards: {number: params['number']})
     end
     if params['num_of_pacients'].present?
       result = result.where(wards: {num_of_pacients: params['num_of_pacients']})
     end


     #Results

     if params['conclusion'].present?
       result = result.where(results: {conclusion: params['conclusion']})
     end
     if params['title'].present?
       result = result.where(results: {title: params['title']})
     end
     if params['rdate'].present?
       result = result.where(results: {rdate: params['rdate']})
     end
     if params['appointment'].present?
       result = result.where(results: {appointment: params['appointment']})
     end
     if params['causes'].present?
       result = result.where(results: {causes: params['causes']})
     end
     if params['first_inspection'].present?
       result = result.where(results: {first_inspection: params['first_inspection']})
     end
     if params['results'].present?
       result = result.where(results: {results: params['results']})
     end

     #Surveys

     if params['cause'].present?
       result = result.where(surveys: {cause: params['cause']})
     end
     if params['entered'].present?
       result = result.where(surveys: {entered: params['entered']})
     end
     if params['ended'].present?
       result = result.where(surveys: {ended: params['ended']})
     end
     if params['epicrisis'].present?
       result = result.where(surveys: {epicrisis: params['epicrisis']})
     end


     result.all
  end
end

Загрузки/моя курсовая/base_app-master/app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Карта пациента создана.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  def search
     if params.has_key?('search')
       @cards = Card.search(params['search'])
     else
       @cards = []
     end
     params['search'] ||= {}

  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Карта пациента изменена.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to surveys_url, notice: 'Карта пациента удалена.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:second_name, :first_name, :last_name, :passport, :insurance, :residence, :created, :allergy, :cart_number, :address_id)
    end
end

Загрузки/моя курсовая/base_app-master/app/helpers/cards_helper.rb
module CardsHelper
end

Загрузки/моя курсовая/base_app-master/app/views/cards/_form.html.haml
= form_for @card do |f|

  = error_messages_for @card
  .row
    .col-md-6
      .form-group
        = f.label :second_name
        = f.text_field :second_name
        = f.error_messages_for(:second_name)
  .row
    .col-md-6
      .form-group
        = f.label :first_name
        = f.text_field :first_name
        = f.error_messages_for(:first_name)
  .row
    .col-md-6
      .form-group
        = f.label :last_name
        = f.text_field :last_name
        = f.error_messages_for(:last_name)
  .row
    .col-md-6
      .form-group
        = f.label :passport
        = f.text_field :passport
        = f.error_messages_for(:passport)
  .row
    .col-md-6
      .form-group
        = f.label :insurance
        = f.number_field :insurance
        = f.error_messages_for(:insurance)
  .row
    .col-md-6
      .form-group
        = f.label :residence
        = f.text_field :residence, class: 'form-control'
        = f.error_messages_for(:residence)
  .row
    .col-md-6
      .form-group
        = f.label :created
        .input-group.date.datepicker
          = f.text_field(:created, value: lnil(f.object.created),
          class: 'form-control')
          %span.input-group-addon
            %span.glyphicon.glyphicon-calendar
        = f.error_messages_for(:created)
  .row
    .col-md-6
      .form-group
        = f.label :allergy
        = f.text_field :allergy, class: 'form-control'
        = f.error_messages_for(:allergy)
  .row
    .col-md-6
      .form-group
        = f.label :cart_number
        = f.number_field :cart_number, class: 'form-control'
        = f.error_messages_for(:cart_number)

  - if is_admin?
    .form-actions.bottom20
      = f.submit nil, class: 'btn btn-primary'
  - else
    %h3 Вносить изменения(регистрировать новые) может только администратор

Загрузки/моя курсовая/base_app-master/app/views/cards/edit.html.haml
=breadcrumb_tag do
  %li.active
    = t('headers.cards.edit')
  %li
    = link_to(@card.cart_number, @card)
  %li
    = link_to 'Карты', cards_path
  %li
    Больница

.page-header
  %h1= t('headers.cards.edit')

= render 'form'

Загрузки/моя курсовая/base_app-master/app/views/cards/index.html.haml
=breadcrumb_tag do
  %li.active
    Карты
  %li
    Больница

%h1= t('app.cards.index')
- if is_admin?
  = link_to new_card_path, class: 'btn btn-success' do
    = fa_icon :plus
    = t('buttons.new.card')
%table.table.table-hover.table-striped.center
  %caption
  %thead
    %tr
      %th= Card.human_attribute_name(:second_name)
      %th= Card.human_attribute_name(:first_name)
      %th= Card.human_attribute_name(:last_name)
      %th= Card.human_attribute_name(:passport)
      %th= Card.human_attribute_name(:insurance)
      %th= Card.human_attribute_name(:residence)
      %th= Card.human_attribute_name(:allergy)
      %th= Card.human_attribute_name(:cart_number)
      %th.p50
      %th.p50
      %th.p50

  %tbody
    - @cards.each do |card|
      %tr
        %td{:data => {:label => (Card.human_attribute_name(:second_name))}}
          = card.second_name
        %td{:data => {:label => (Card.human_attribute_name(:first_name))}}
          = card.first_name
        %td{:data => {:label => (Card.human_attribute_name(:last_name))}}
          = card.last_name
        %td{:data => {:label => (Card.human_attribute_name(:passport))}}
          = card.passport
        %td{:data => {:label => (Card.human_attribute_name(:residence))}}
          = card.residence
        %td{:data => {:label => (Card.human_attribute_name(:created))}}
          = card.created
        %td{:data => {:label => (Card.human_attribute_name(:allergy))}}
          = card.allergy
        %td{:data => {:label => (Card.human_attribute_name(:cart_number))}}
          = card.cart_number
        %td.right
          = link_to card, class: 'btn btn-success' do
            = fa_icon :eye
        - if is_admin?
          %td.right
            = link_to edit_card_path(card), class: 'btn btn-info' do
              = fa_icon :edit
        - if is_admin?
          %td.right
            = link_to card, :method => :delete, :data => { :confirm => t('helpers.sure') }, class: 'btn btn-danger' do
              = fa_icon :times

Загрузки/моя курсовая/base_app-master/app/views/cards/new.html.haml
=breadcrumb_tag do
  %li.active
    = t('headers.cards.new')
  %li
    = link_to 'Карты', cards_path
  %li
    Больница
.page-header
  %h1= t('headers.cards.new')
= render 'form'

Загрузки/моя курсовая/base_app-master/app/views/cards/search.html.haml
=breadcrumb_tag do
  %li.active
    = t('headers.cards.search')
  %li
    =link_to 'Пациенты', cards_path
  %li
    Больница

.page-header
  %h1= t('headers.cards.search')

= form_tag search_cards_path(), method: :get do
  .well
    %h3= t('headers.cards.card')
    .row
      .col-md-4
        .form-group
        =Card.human_attribute_name(:second_name)
        =text_field_tag 'search[second_name]', params['search']['second_name'],class: 'form-control'
      .col-md-4
        .form-group
        =Card.human_attribute_name(:first_name)
        =text_field_tag 'search[first_name]', params['search']['first_name'],class: 'form-control'
      .col-md-4
        .form-group
        =Card.human_attribute_name(:last_name)
        =text_field_tag 'search[last_name]', params['search']['last_name'],class: 'form-control'
      .col-md-4
        .form-group
        =Card.human_attribute_name(:passport)
        =number_field_tag 'search[passport]', params['search']['passport'],class: 'form-control'
      .col-md-4
        .form-group
        =Card.human_attribute_name(:insurance)
        =text_field_tag 'search[insurance]', params['search']['insurance'],class: 'form-control'
      .col-md-4
        .form-group
        =Card.human_attribute_name(:residence)
        =text_field_tag 'search[residence]', params['search']['residence'],class: 'form-control'
      .col-md-4
        .form-group
        =Card.human_attribute_name(:created)
        =date_field_tag 'search[created]', params['search']['created'],class: 'form-control'
      .col-md-4
        .form-group
        =Card.human_attribute_name(:allergy)
        =text_field_tag 'search[allergy]', params['search']['allergy'],class: 'form-control'
      .col-md-4
        .form-group
        =Card.human_attribute_name(:cart_number)
        =number_field_tag 'search[cart_number]', params['search']['cart_number'],class: 'form-control'

    %h3= t('headers.cards.ward')
    .row
      .col-md-4
        .form-group
        =Ward.human_attribute_name(:department)
        =text_field_tag 'search[department]', params['search']['department'],class: 'form-control'
      .col-md-4
        .form-group
        =Ward.human_attribute_name(:floor)
        =number_field_tag 'search[floor]', params['search']['floor'],class: 'form-control'
      .col-md-4
        .form-group
        =Ward.human_attribute_name(:capacity)
        =number_field_tag 'search[capacity]', params['search']['capacity'],class: 'form-control'
      .col-md-4
        .form-group
        =Ward.human_attribute_name(:number)
        =number_field_tag 'search[number]', params['search']['number'],class: 'form-control'
      .col-md-4
        .form-group
        =Ward.human_attribute_name(:num_of_pacients)
        =number_field_tag 'search[num_of_pacients]', params['search']['num_of_pacients'],class: 'form-control'

    %h3= t('headers.cards.result')
    .row
      .col-md-4
        .form-group
        =Result.human_attribute_name(:conclusion)
        =text_field_tag 'search[conclusion]', params['search']['conclusion'],class: 'form-control'
      .col-md-4
        .form-group
        =Result.human_attribute_name(:title)
        =text_field_tag 'search[title]', params['search']['title'],class: 'form-control'
      .col-md-4
        .form-group
        =Result.human_attribute_name(:rdate)
        =date_field_tag 'search[rdate]', params['search']['rdate'],class: 'form-control'
      .col-md-4
        .form-group
        =Result.human_attribute_name(:appointment)
        =text_field_tag 'search[appointment]', params['search']['appointment'],class: 'form-control'
      .col-md-4
        .form-group
        =Result.human_attribute_name(:causes)
        =text_field_tag 'search[causes]', params['search']['causes'],class: 'form-control'
      .col-md-4
        .form-group
        =Result.human_attribute_name(:first_inspection)
        =text_field_tag 'search[first_inspection]', params['search']['first_inspection'],class: 'form-control'
      .col-md-4
        .form-group
        =Result.human_attribute_name(:results)
        =text_field_tag 'search[results]', params['search']['results'],class: 'form-control'

    %h3= t('headers.cards.survey')
    .row
      .col-md-4
        .form-group
        =Survey.human_attribute_name(:cause)
        =text_field_tag 'search[cause]', params['search']['cause'],class: 'form-control'
      .col-md-4
        .form-group
        =Survey.human_attribute_name(:entered)
        =text_field_tag 'search[entered]', params['search']['entered'],class: 'form-control'
      .col-md-4
        .form-group
        =Survey.human_attribute_name(:ended)
        =date_field_tag 'search[ended]', params['search']['ended'],class: 'form-control'
      .col-md-4
        .form-group
        =Survey.human_attribute_name(:epicrisis)
        =text_field_tag 'search[epicrisis]', params['search']['epicrisis'],class: 'form-control'


  .actions
    =submit_tag t('buttons.search.card'), class: 'bnt btn-primary'
.page-header
  %h1= t('headers.cards.found') + ": " + @cards.size.to_s
- if @cards.size > 0
  %table.table.table-hover.table-striped.center
    %caption
    %thead
      %tr
        %th= Card.human_attribute_name(:second_name)
        %th= Card.human_attribute_name(:first_name)
        %th= Card.human_attribute_name(:last_name)
        %th= Card.human_attribute_name(:passport)
        %th= Card.human_attribute_name(:insurance)
        %th= Card.human_attribute_name(:residence)
        %th= Card.human_attribute_name(:allergy)
        %th= Card.human_attribute_name(:cart_number)
        %th.p50
        %th.p50
        %th.p50

    %tbody
      - @cards.each do |card|
        %tr
          %td{:data => {:label => (Card.human_attribute_name(:second_name))}}
            = card.second_name
          %td{:data => {:label => (Card.human_attribute_name(:first_name))}}
            = card.first_name
          %td{:data => {:label => (Card.human_attribute_name(:last_name))}}
            = card.last_name
          %td{:data => {:label => (Card.human_attribute_name(:passport))}}
            = card.passport
          %td{:data => {:label => (Card.human_attribute_name(:residence))}}
            = card.residence
          %td{:data => {:label => (Card.human_attribute_name(:created))}}
            = card.created
          %td{:data => {:label => (Card.human_attribute_name(:allergy))}}
            = card.allergy
          %td{:data => {:label => (Card.human_attribute_name(:cart_number))}}
            = card.cart_number

Загрузки/моя курсовая/base_app-master/app/views/cards/show.html.haml
=breadcrumb_tag do
  %li.active
    = @card.id
  %li
    = link_to 'Карты', cards_path
  %li
    Больница

%h1= @Сard_id

%dl
  %dt= Card.human_attribute_name(:second_name)
  %dd= @card.second_name
  %dt= Card.human_attribute_name(:first_name)
  %dd= @card.first_name
  %dt= Card.human_attribute_name(:last_name)
  %dd= @card.last_name
  %dt= Card.human_attribute_name(:passport)
  %dd= @card.passport
  %dt= Card.human_attribute_name(:insurance)
  %dd= @card.insurance
  %dt= Card.human_attribute_name(:residence)
  %dd= @card.residence
  %dt= Card.human_attribute_name(:created)
  %dd= @card.created
  %dt= Card.human_attribute_name(:allergy)
  %dd= @card.allergy
  %dt= Card.human_attribute_name(:cart_number)
  %dd= @card.cart_number