Загрузки/моя курсовая/base_app-master/config/routes.rb
Rails.application.routes.draw do
  post 'fill_result_form' => 'surveys#fill_result_form'
  post 'fill_ward_form' => 'surveys#fill_ward_form'
  post 'fill_card_form' => 'surveys#fill_card_form'

  resources :results
  resources :surveys
  resources :wards
  resources :cards do
     collection do
       get :search
     end
   end
  resources :role_users
  resources :roles
  resources :password_resets

  get 'welcome/index', as: :welcome
  get 'welcome/insufficient_privileges', as: :ip
  get 'login' => 'welcome#new', :as => :login
  get 'logout' => 'welcome#destroy', :as => :logout
  post 'try_login' => 'welcome#create', :as => :try_login
  root 'welcome#index'

  resources :users do
    member do
      get :activate
    end
  end

end

Загрузки/моя курсовая/base_app-master/app/models/ward.rb
class Ward < ActiveRecord::Base
  has_many :surveys, dependent: :destroy

  validates :department, presence:true, length: {maximum: 128}
  validates :floor, presence:true, numericality:
  {only_integer: true, greater_than_or_equal_to: 1}
  validates :capacity, presence:true, numericality:
  {only_integer: true, greater_than_or_equal_to: 1}
  validates :number, presence:true, uniqueness:true, numericality:
  {only_integer: true, greater_than_or_equal_to: 1}
end

Загрузки/моя курсовая/base_app-master/app/controllers/wards_controller.rb
class WardsController < ApplicationController
  before_action :set_ward, only: [:show, :edit, :update, :destroy]

  # GET /wards
  # GET /wards.json
  def index
    @wards = Ward.all
  end

  # GET /wards/1
  # GET /wards/1.json
  def show
  end

  # GET /wards/new
  def new
    @ward = Ward.new
  end

  # GET /wards/1/edit
  def edit
  end

  # POST /wards
  # POST /wards.json
  def create
    @ward = Ward.new(ward_params)

    respond_to do |format|
      if @ward.save
        format.html { redirect_to @ward, notice: 'Палата создана.' }
        format.json { render :show, status: :created, location: @ward }
      else
        format.html { render :new }
        format.json { render json: @ward.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wards/1
  # PATCH/PUT /wards/1.json
  def update
    respond_to do |format|
      if @ward.update(ward_params)
        format.html { redirect_to @ward, notice: 'Палата изменена.' }
        format.json { render :show, status: :ok, location: @ward }
      else
        format.html { render :edit }
        format.json { render json: @ward.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wards/1
  # DELETE /wards/1.json
  def destroy
    @ward.destroy
    respond_to do |format|
      format.html { redirect_to surveys_url, notice: 'Палата удалена.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ward
      @ward = Ward.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ward_params
      params.require(:ward).permit(:department, :floor, :capacity, :number, :num_of_pacients)
    end
end

Загрузки/моя курсовая/base_app-master/app/helpers/wards_helper.rb
module WardsHelper
end

Загрузки/моя курсовая/base_app-master/app/views/wards/_form.html.haml
= form_for @ward do |f|

  = error_messages_for @ward
  .row
    .col-md-6
      .form-group
        = f.label :department
        = f.number_field :department, class: 'form-control'
        = f.error_messages_for(:department)
  .row
    .col-md-6
      .form-group
        = f.label :floor
        = f.number_field :floor, class: 'form-control'
        = f.error_messages_for(:floor)
  .row
    .col-md-6
      .form-group
        = f.label :capacity
        = f.number_field :capacity, class: 'form-control'
        = f.error_messages_for(:capacity)
  .row
    .col-md-6
      .form-group
        = f.label :number
        = f.number_field :number, class: 'form-control'
        = f.error_messages_for(:number)
  .row
    .col-md-6
      .form-group
        = f.label :num_of_pacients
        = f.number_field :num_of_pacients, class: 'form-control'
        = f.error_messages_for(:num_of_pacients)

  - if is_admin?
    .form-actions.bottom20
      = f.submit nil, class: 'btn btn-primary'
  - else
    %h3 Вносить изменения(регистрировать новые) может только администратор

Загрузки/моя курсовая/base_app-master/app/views/wards/edit.html.haml
=breadcrumb_tag do
  %li.active
    = t('headers.wards.edit')
  %li
    = link_to(@ward.number, @ward)
  %li
    = link_to 'Палаты', wards_path
  %li
    Больница

.page-header
  %h1= t('headers.wards.edit')

= render 'form'

Загрузки/моя курсовая/base_app-master/app/views/wards/index.html.haml
=breadcrumb_tag do
  %li.active
    Палаты
  %li
    Больница

%h1= t('app.wards.index')
- if is_admin?
  = link_to new_ward_path, class: 'btn btn-success' do
    = fa_icon :plus
    = t('buttons.new.ward')
.table-responsive
  %table.table.table-hover.table-striped.center
    %caption
    %thead
      %tr
        %th= Ward.human_attribute_name(:department)
        %th= Ward.human_attribute_name(:floor)
        %th= Ward.human_attribute_name(:capacity)
        %th= Ward.human_attribute_name(:number)
        %th= Ward.human_attribute_name(:num_of_pacients)
        %th.p50
        %th.p50
        %th.p50

    %tbody
      - @wards.each do |ward|
        %tr
          %td{:data => {:label => (Ward.human_attribute_name(:department))}}
            = ward.department
          %td{:data => {:label => (Ward.human_attribute_name(:floor))}}
            = ward.floor
          %td{:data => {:label => (Ward.human_attribute_name(:capacity))}}
            = ward.capacity
          %td{:data => {:label => (Ward.human_attribute_name(:number))}}
            = ward.number
          %td{:data => {:label => (Ward.human_attribute_name(:num_of_pacients))}}
            = ward.num_of_pacients
          %td.right
            = link_to ward, class: 'btn btn-success' do
              = fa_icon :eye
          - if is_admin?
            %td.right
              = link_to edit_ward_path(ward), class: 'btn btn-info' do
                = fa_icon :edit
          - if is_admin?
            %td.right
              = link_to ward, :method => :delete, :data => { :confirm => t('helpers.sure') }, class: 'btn btn-danger' do
                = fa_icon :times

Загрузки/моя курсовая/base_app-master/app/views/wards/new.html.haml
=breadcrumb_tag do
  %li.active
    = t('headers.wards.new')
  %li
    = link_to 'Палаты', wards_path
  %li
    Больница
.page-header
  %h1= t('headers.wards.new')
= render 'form'

Загрузки/моя курсовая/base_app-master/app/views/wards/show.html.haml
=breadcrumb_tag do
  %li.active
    = @ward.id
  %li
    = link_to 'Палаты', wards_path
  %li
    Больница

%h1= @Ward_id

%dl
  %dt= Ward.human_attribute_name(:department)
  %dt= @ward.department
  %dt= Ward.human_attribute_name(:floor)
  %dt= @ward.floor
  %dt= Ward.human_attribute_name(:capacity)
  %dt= @ward.capacity
  %dt= Ward.human_attribute_name(:number)
  %dt= @ward.number
  %dt= Ward.human_attribute_name(:num_of_pacients)
  %dt= @ward.num_of_pacients