Загрузки/моя курсовая/base_app-master/config/routes.rb
Rails.application.routes.draw do
  post 'fill_result_form' => 'surveys#fill_result_form'
  post 'fill_ward_form' => 'surveys#fill_ward_form'
  post 'fill_card_form' => 'surveys#fill_card_form'

  resources :results
  resources :surveys
  resources :wards
  resources :cards do
     collection do
       get :search
     end
   end
  resources :role_users
  resources :roles
  resources :password_resets

  get 'welcome/index', as: :welcome
  get 'welcome/insufficient_privileges', as: :ip
  get 'login' => 'welcome#new', :as => :login
  get 'logout' => 'welcome#destroy', :as => :logout
  post 'try_login' => 'welcome#create', :as => :try_login
  root 'welcome#index'

  resources :users do
    member do
      get :activate
    end
  end

end

Загрузки/моя курсовая/base_app-master/app/models/result.rb
class Result < ActiveRecord::Base
  has_many :surveys, dependent: :destroy

  validates :conclusion, presence:true, length: {maximum: 128}
  validates :title, presence:true, length: {maximum: 128}
  validates :rdate, presence:true
  validates :appointment, presence:true, length: {maximum: 128}
  validates :causes, presence:true, length: {maximum: 128}
  validates :first_inspection, presence:true, length: {maximum: 128}
  validates :results, presence:true, length: {maximum: 128}
end

Загрузки/моя курсовая/base_app-master/app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :set_result, only: [:show, :edit, :update, :destroy]

  # GET /results
  # GET /results.json
  def index
    @results = Result.all
  end

  # GET /results/1
  # GET /results/1.json
  def show
  end

  # GET /results/new
  def new
    @result = Result.new
  end

  # GET /results/1/edit
  def edit
  end

  # POST /results
  # POST /results.json
  def create
    @result = Result.new(result_params)

    respond_to do |format|
      if @result.save
        format.html { redirect_to @result, notice: 'Результат обследования созданы.' }
        format.json { render :show, status: :created, location: @result }
      else
        format.html { render :new }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /results/1
  # PATCH/PUT /results/1.json
  def update
    respond_to do |format|
      if @result.update(result_params)
        format.html { redirect_to @result, notice: 'Результат обследования изменен.' }
        format.json { render :show, status: :ok, location: @result }
      else
        format.html { render :edit }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /results/1
  # DELETE /results/1.json
  def destroy
    @result.destroy
    respond_to do |format|
      format.html { redirect_to surveys_url, notice: 'Результат обследования удален.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_result
      @result = Result.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def result_params
      params.require(:result).permit(:conclusion, :title, :rdate, :appointment, :causes, :first_inspection, :results)
    end
end

Загрузки/моя курсовая/base_app-master/app/helpers/results_helper.rb
module ResultsHelper
end

Загрузки/моя курсовая/base_app-master/app/views/results/_form.html.haml
= form_for @result do |f|

  = error_messages_for @result
  .row
    .col-md-6
      .form-group
        = f.label :conclusion
        = f.text_field :conclusion, class: 'form-control'
        = f.error_messages_for(:conclusion)
  .row
    .col-md-6
      .form-group
        = f.label :title
        = f.text_field :title, class: 'form-control'
        = f.error_messages_for(:title)
  .row
    .col-md-6
      .form-group
        = f.label :rdate
        .input-group.date.datepicker
          = f.text_field(:rdate, value: lnil(f.object.rdate),
          class: 'form-control')
          %span.input-group-addon
            %span.glyphicon.glyphicon-calendar
        = f.error_messages_for(:rdate)
  .row
    .col-md-6
      .form-group
        = f.label :appointment
        = f.text_field :appointment, class: 'form-control'
        = f.error_messages_for(:appointment)
  .row
    .col-md-6
      .form-group
        = f.label :causes
        = f.text_field :causes, class: 'form-control'
        = f.error_messages_for(:causes)
  .row
    .col-md-6
      .form-group
        = f.label :first_inspection
        = f.text_field :first_inspection, class: 'form-control'
        = f.error_messages_for(:first_inspection)
  .row
    .col-md-6
      .form-group
        = f.label :results
        = f.text_field :results, class: 'form-control'
        = f.error_messages_for(:results)

  - if is_admin?
    .form-actions.bottom20
      = f.submit nil, class: 'btn btn-primary'
  - else
    %h3 Вносить изменения(регистрировать новые) может только администратор

Загрузки/моя курсовая/base_app-master/app/views/results/edit.html.haml
=breadcrumb_tag do
  %li.active
    = t('headers.results.edit')
  %li
    = link_to(@result.title, @result)
  %li
    = link_to 'Палаты', results_path
  %li
    Больница

.page-header
  %h1= t('headers.results.edit')

= render 'form'

Загрузки/моя курсовая/base_app-master/app/views/results/index.html.haml
=breadcrumb_tag do
  %li.active
    Результаты обследования
  %li
    Больница

%h1= t('app.results.index')
- if is_admin?
  = link_to new_result_path, class: 'btn btn-success' do
    = fa_icon :plus
    = t('buttons.new.result')
  %table.table.table-hover.table-striped.center
    %caption
    %thead
      %tr
        %th= Result.human_attribute_name(:conclusion)
        %th= Result.human_attribute_name(:title)
        %th= Result.human_attribute_name(:rdate)
        %th= Result.human_attribute_name(:appointment)
        %th= Result.human_attribute_name(:causes)
        %th= Result.human_attribute_name(:first_inspection)
        %th= Result.human_attribute_name(:results)
        %th.p50
        %th.p50
        %th.p50

    %tbody
      - @results.each do |result|
        %tr
          %td= result.conclusion
          %td= result.title
          %td= result.rdate
          %td= result.appointment
          %td= result.causes
          %td= result.first_inspection
          %td= result.results
          %td
            = link_to result, class: 'btn btn-success' do
              = fa_icon :eye
          - if is_admin?
            %td
              = link_to edit_result_path(result), class: 'btn btn-info' do
                = fa_icon :edit
            %td
              = link_to result, :method => :delete, :data => { :confirm => t('helpers.sure') }, class: 'btn btn-danger' do
                = fa_icon :times

Загрузки/моя курсовая/base_app-master/app/views/results/new.html.haml
=breadcrumb_tag do
  %li.active
    = t('headers.results.new')
  %li
    = link_to 'Результаты', results_path
  %li
    Больница
.page-header
  %h1= t('headers.results.new')
= render 'form'

Загрузки/моя курсовая/base_app-master/app/views/results/show.html.haml
=breadcrumb_tag do
  %li.active
    = @result.id
  %li
    = link_to 'Результаты', results_path
  %li
    Больница

%h1= @result_id

%dl
  %dt= Result.human_attribute_name(:conclusion)
  %dd= @result.conclusion
  %dt= Result.human_attribute_name(:title)
  %dd= @result.title
  %dt= Result.human_attribute_name(:rdate)
  %dd= @result.rdate
  %dt= Result.human_attribute_name(:appointment)
  %dd= @result.appointment
  %dt= Result.human_attribute_name(:causes)
  %dd= @result.causes
  %dt= Result.human_attribute_name(:first_inspection)
  %dd= @result.first_inspection
  %dt= Result.human_attribute_name(:results)
  %dd= @result.results